# Generated by Django 3.0.7 on 2021-11-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('number_of_groups', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='classslotdetails',
            name='max_capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='GroupDiscussionLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('group_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.GroupDiscussion')),
            ],
        ),
    ]
